#!name = 19in1 VIP All-in-One
#!desc = Gộp 19 cấu hình VIP của các ứng dụng bẻ khóa. Tối ưu hóa và cá nhân hóa bởi HuyCongDev05.

[General]
# From YouTube
private-ip-answer = true
bypass-system = true
ipv6 = false
prefer-ipv6 = false
dns-server = 94.140.14.14, 94.140.15.15
fallback-dns-server = 76.76.2.0, 76.76.10.0
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local, captive.apple.com
tun-excluded-routes = 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.88.99.0/24, 192.168.0.0/16, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 255.255.255.255/32, 239.255.255.250/32

[Rule]
# From YouTube
RULE-SET,https://raw.githubusercontent.com/bigdargon/hostsVN/master/option/hostsVN-surge-rule.conf,REJECT
RULE-SET,https://raw.githubusercontent.com/bigdargon/hostsVN/master/option/hostsVN-surge-exceptions-rule.conf,DIRECT
DOMAIN-SUFFIX,googlevideo.com,DIRECT
DOMAIN-SUFFIX,youtubei.googleapis.com,DIRECT
IP-CIDR,0.0.0.0/32,REJECT,no-resolve
FINAL,DIRECT

[URL Rewrite]
# From YouTube
^https?:\/\/[\w-]+\.googlevideo\.com\/initplayback.+&oad _ REJECT-IMG
https?:\/\/.+\.googlevideo\.com\/ptracking\?pltype=adhost reject header
https?:\/\/.+\.youtube\.com\/api\/stats\/.+adformat reject header
https?:\/\/m\.youtube\.com\/_get_ads reject header
https?:\/\/pagead2\.googlesyndication\.com\/pagead\/ reject header
https?:\/\/s\.youtube\.com\/api\/stats\/watchtime?adformat reject header
https?:\/\/youtubei\.googleapis\.com/.+ad_break reject header

[Header Rewrite]
# From Spotify
http-request ^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/user-customization-service\/v1\/customize$ header-del if-none-match

[Script]
# From AlightMotion
AlightMotion=type=http-response,pattern=^https:\/\/us-central1-alight-creative\.cloudfunctions\.net\/getAccountStatusAndLicenses,requires-body=true,max-size=131072,timeout=10,script-path=https://raw.githubusercontent.com/HuyCongDev05/app-crack/main/AlightMotion/AlightMotion.js
# From BeautyPlus
BeautyPlus=type=http-response,pattern=https:\/\/(api\.mr\.pixocial\.com\/v1\/manual_unlock|newbeee-api\.beautyplus\.com\/api\/v1\/asset\/balance),requires-body=true,max-size=-1,timeout=60,script-path=https://raw.githubusercontent.com/HuyCongDev05/app-crack/main/BeautyPlus/BeautyPlus.js
# From CamScanner
Camscanner=type=http-response,pattern=https:\/\/(api|api-cs.*)\.intsig\.net\/purchase\/cs\/query_prop,requires-body=1,script-path=https://raw.githubusercontent.com/HuyCongDev05/app-crack/main/CamScanner/camscanner.js
# From FainTV
FainTV=type=http-response,pattern=^http:\/\/ftvn\.hawsing\.com\.tw:3000\/client\/login,requires-body=1,script-path=https://raw.githubusercontent.com/HuyCongDev05/app-crack/main/FainTV/fatv.js
# From IconKiller
icon Killer=type=http-response,pattern=^http[s]?:\/\/api.yonekura.cn\/3.6.8\/uicommon\/getuser,requires-body=1,script-path=https://raw.githubusercontent.com/HuyCongDev05/app-crack/main/IconKiller/lcon.js
# From iScreen
iScreenn=type=http-response,pattern=^https:\/\/buy\.itunes\.apple\.com\/verifyReceipt$,requires-body=1,script-path=https://raw.githubusercontent.com/HuyCongDev05/app-crack/main/iScreen/iScreenn.js
# From Kinemaster
Kinemaster=type=http-response,pattern=^https:\/\/api-account\.kinemasters\.com\/v\d\/user\/subscribe$,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/HuyCongDev05/app-crack/main/Kinemaster/Kinemaster.js
# From Lightroom
LightRoom=type=http-response,pattern=^https:\/\/photos\.adobe\.io\/v2\/accounts*,requires-body=1,script-path=https://raw.githubusercontent.com/HuyCongDev05/app-crack/main/Lightroom/lightroom.js
# From Locket
revenuecat=type=http-response,pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts$|subscribers\/[^/]+$),requires-body=true,max-size=-1,timeout=60,script-path=https://raw.githubusercontent.com/HuyCongDev05/app-crack/main/Locket/revenuecat.js
deleteHeader = type=http-request,pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts|subscribers),script-path=https://raw.githubusercontent.com/HuyCongDev05/app-crack/main/Locket/deleteHeader.js,timeout=60
# From Nicegram
Nicegram VIP=type=http-request,pattern=^https?:\/\/restore-access\.indream\.app\/restoreAccess\?id=\w+$,requires-body=0,max-size=0,script-path=https://raw.githubusercontent.com/HuyCongDev05/app-crack/main/Nicegram/Nicegram.js,script-update-interval=0
# From PhotoRoom
PhotoRoom=type=http-response,pattern=^https?:\/\/api\.revenuecat\.com\/v1\/(subscribers\/[^\/]+$|receipts$),requires-body=1,script-path=https://raw.githubusercontent.com/HuyCongDev05/app-crack/main/PhotoRoom/PhotoRoom.js
# From PicsArt
Picsart=type=http-response,pattern=https:\/\/api\.(picsart|meiease)\.c(n|om)\/users\/show\/me\.json,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/HuyCongDev05/app-crack/main/PicsArt/PicsArt.js
# From Pixelcut
Pixelcut=type=http-response,pattern=https://api.revenuecat.com/v1/(receipts|subscribers)/*,requires-body=1,script-path=https://raw.githubusercontent.com/HuyCongDev05/app-crack/main/Pixelcut/pixelcut.js
# From Spotify
spotify-json = type=http-request,pattern=^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/(artistview\/v1\/artist|album-entity-view\/v2\/album)\/,requires-body=0,script-path=https://raw.githubusercontent.com/HuyCongDev05/app-crack/main/Spotify/spotify-json.js
spotify-proto = type=http-response,pattern=^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$,requires-body=1,binary-body-mode=1,max-size=0,script-path=https://raw.githubusercontent.com/HuyCongDev05/app-crack/main/Spotify/spotify-proto.js,script-update-interval=0
# From Truecaller
Truecaller=type=http-response,pattern=^https://premium-(.+)\.truecaller\.com/v\d/(subscriptions|products\/apple),requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/duyvinh09/Module_IOS/refs/heads/main/js/TrueCaller.js
# From VivaCut
Vivacut=type=http-response,pattern=^https:\/\/medi\.dxzzy321\.top\/api\/rest\/commerce\/integrate\/vip\/perform,requires-body=1,script-path=https://raw.githubusercontent.com/HuyCongDev05/app-crack/main/VivaCut/vivacut.js
# From VSCO
VSCO=type=http-request,pattern=^https?:\/\/api\.revenuecat\.com\/v\d\/subscribers\/,script-path=https://raw.githubusercontent.com/HuyCongDev05/app-crack/main/VSCO/vsco.js
VSCO1=type=http-response,pattern=^https?:\/\/api\.revenuecat\.com\/v\d\/subscribers\/,requires-body=1,script-path=https://raw.githubusercontent.com/HuyCongDev05/app-crack/main/VSCO/vsco.js
# From Wink
WinkForeverVipCrack.js=type=http-response,pattern=^https?:\/\/api-sub\.meitu\.com\/v2\/user\/vip_info_by_group\.json,requires-body=1,script-path=https://raw.githubusercontent.com/HuyCongDev05/app-crack/main/Wink/WinkForeverVipCrack.js
# From YouTube
youtube.response = type=http-response,pattern=^https:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/(browse|next|player|search|reel\/reel_watch_sequence|guide|account\/get_setting|get_watch),requires-body=1,max-size=-1,binary-body-mode=1,script-path=https://raw.githubusercontent.com/HuyCongDev05/app-crack/main/YouTube/youtube.response.js,argument="{\"lyricLang\":\"{{null}}\",\"captionLang\":\"{{{null}}}\",\"blockUpload\":{{{true}}},\"blockImmersive\":{{{true}}},\"debug\":{{{false}}}}"

[MITM]
hostname = %APPEND% *.googlevideo.com, *spclient.spotify.com, ap*.intsig.net, api-account.kinemasters.com, api-sub.meitu.com, api.meiease.c*, api.mr.pixocial.com, api.picsart.c*, api.revenuecat.com, api.yonekura.cn, buy.itunes.apple.com, ftvn.hawsing.com, medi.dxzzy321.top, newbeee-api.beautyplus.com, photos.adobe.io, premium*.truecaller.com, restore-access.indream.app, spclient.wg.spotify.com, us-central1-alight-creative.cloudfunctions.net, youtubei.googleapis.com
enable = true
